#!/bin/bash
#SVBONY CCD SV905C2.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_N=1000
#SVBONY CCD SV905C2.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_S=0
#SVBONY CCD SV905C2.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_W=0
#SVBONY CCD SV905C2.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_E=2000
#iOptronV3.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_N=1400
#iOptronV3.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_S=0
#iOptronV3.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_W=1000
#iOptronV3.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_E=0

indi_setprop "iOptronV3.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_N=500.0"
indi_setprop "iOptronV3.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_W=500.0"
indi_setprop "SVBONY CCD SV905C2.TELESCOPE_TIMED_GUIDE_NS.TIMED_GUIDE_N=500.0"
indi_setprop "SVBONY CCD SV905C2.TELESCOPE_TIMED_GUIDE_WE.TIMED_GUIDE_W=500.0"
indi_getprop | grep TIMED
